<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="2" hostname="Chohees-MBP" name="automationcode15thApr2023.RediffListenerLoginTest" tests="5" failures="0" timestamp="2023-04-22T10:51:54 EDT" time="77.916" errors="1">
  <testcase name="clickOnSigninLink" time="18.920" classname="automationcode15thApr2023.RediffListenerLoginTest"/>
  <system-out/>
  <testcase name="enterCredentials" time="18.729" classname="automationcode15thApr2023.RediffListenerLoginTest">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method automationcode15thApr2023.RediffListenerLoginTest.enterCredentials() didn&#039;t finish within the time-out 1000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method automationcode15thApr2023.RediffListenerLoginTest.enterCredentials() didn't finish within the time-out 1000
at org.testng.internal.MethodInvocationHelper.invokeWithTimeoutWithNewExecutor(MethodInvocationHelper.java:384)
at org.testng.internal.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:283)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:604)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- enterCredentials -->
  <system-out/>
  <testcase name="clickOnsigninButton" time="10.480" classname="automationcode15thApr2023.RediffListenerLoginTest">
    <skipped/>
  </testcase> <!-- clickOnsigninButton -->
  <system-out/>
  <testcase name="clickOnLogoutLink" time="29.787" classname="automationcode15thApr2023.RediffListenerLoginTest"/>
  <system-out/>
  <testcase name="clickOnRediffHomeLink" classname="automationcode15thApr2023.RediffListenerLoginTest">
    <skipped/>
  </testcase> <!-- clickOnRediffHomeLink -->
  <system-out/>
</testsuite> <!-- automationcode15thApr2023.RediffListenerLoginTest -->
